<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.mycompany</groupId>
    <artifactId>FacturacionMavenMariadb</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>
    <build>
        <resources>
            <resource>                
                <targetPath>META-INF</targetPath>
                <directory>src</directory>
                <includes>
                    <include>jax-ws-catalog.xml</include>
                    <include>wsdl/**</include>
                </includes>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
            </resource>
        </resources>
        <plugins>                 
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <release>26</release>
                </configuration>
            </plugin>

            <plugin>
                <groupId>com.sun.xml.ws</groupId>
                <artifactId>jaxws-maven-plugin</artifactId>
                <version>4.0.3</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>wsimport</goal>
                        </goals>
                        <configuration>
                            <wsdlFiles>
                                <wsdlFile>rproxy.cobituc.info_5480/WsBoreal/servlet/awsboreal.wsdl</wsdlFile>
                            </wsdlFiles>
                            <packageName>ClienteBoreal</packageName>
                            <vmArgs>
                                <vmArg>-Djavax.xml.accessExternalSchema=all</vmArg>
                            </vmArgs>
                            <wsdlLocation>http://rproxy.cobituc.info:5480/WsBoreal/servlet/awsboreal?wsdl</wsdlLocation>
                            <staleFile>${project.build.directory}/jaxws/stale/awsboreal.stale</staleFile>
                        </configuration>
                        <id>wsimport-generate-awsboreal</id>
                        <phase>generate-sources</phase>
                    </execution>
                    <execution>
                        <goals>
                            <goal>wsimport</goal>
                        </goals>
                        <configuration>
                            <wsdlFiles>
                                <wsdlFile>ws.ipsst.gov.ar_8543/ws_expendio/aafiliadopuedeconsumir.aspx.wsdl</wsdlFile>
                            </wsdlFiles>
                            <packageName>ClienteIPSST1</packageName>
                            <vmArgs>
                                <vmArg>-Djavax.xml.accessExternalSchema=all</vmArg>  
                                <vmArg>-Djsse.enableSNIExtension=false</vmArg>  
                                <vmOptions>-Djsse.enableSNIExtension=false</vmOptions>
                            </vmArgs>
                            <wsdlLocation>https://ws.ipsst.gov.ar:8543/ws_expendio/aafiliadopuedeconsumir.aspx?wsdl</wsdlLocation>
                            <staleFile>${project.build.directory}/jaxws/stale/aafiliadopuedeconsumir.aspx.stale</staleFile>
                        </configuration>
                        <id>wsimport-generate-aafiliadopuedeconsumir.aspx</id>
                        <phase>generate-sources</phase>
                    </execution>
                    <execution>
                        <goals>
                            <goal>wsimport</goal>
                        </goals>
                        <configuration>
                            <wsdlFiles>
                                <wsdlFile>rproxy.cobituc.info/ws_expendio/aafiliadodatostraer.aspx.wsdl</wsdlFile>
                            </wsdlFiles>
                            <packageName>ClienteIPSST2</packageName>
                            <vmArgs>
                                <vmArg>-Djavax.xml.accessExternalSchema=all</vmArg>
                            </vmArgs>
                            <wsdlLocation>http://rproxy.cobituc.info/ws_expendio/aafiliadodatostraer.aspx?wsdl</wsdlLocation>
                            <staleFile>${project.build.directory}/jaxws/stale/aafiliadodatostraer.aspx.stale</staleFile>
                        </configuration>
                        <id>wsimport-generate-aafiliadodatostraer.aspx</id>
                        <phase>generate-sources</phase>
                    </execution>
                    <execution>
                        <goals>
                            <goal>wsimport</goal>
                        </goals>
                        <configuration>
                            <wsdlFiles>
                                <wsdlFile>rproxy.cobituc.info/ws_expendio/aordenautorizar.aspx.wsdl</wsdlFile>
                            </wsdlFiles>
                            <packageName>ClienteIPSST3</packageName>
                            <vmArgs>
                                <vmArg>-Djavax.xml.accessExternalSchema=all</vmArg>
                            </vmArgs>
                            <wsdlLocation>http://rproxy.cobituc.info/ws_expendio/aordenautorizar.aspx?wsdl</wsdlLocation>
                            <staleFile>${project.build.directory}/jaxws/stale/aordenautorizar.aspx.stale</staleFile>
                        </configuration>
                        <id>wsimport-generate-aordenautorizar.aspx</id>
                        <phase>generate-sources</phase>
                    </execution>
                    <execution>
                        <goals>
                            <goal>wsimport</goal>
                        </goals>
                        <configuration>
                            <wsdlFiles>
                                <wsdlFile>rproxy.cobituc.info/ws_expendio/aordenvalidar.aspx.wsdl</wsdlFile>
                            </wsdlFiles>
                            <packageName>ClienteIPSST4</packageName>
                            <vmArgs>
                                <vmArg>-Djavax.xml.accessExternalSchema=all</vmArg>
                            </vmArgs>
                            <wsdlLocation>http://rproxy.cobituc.info/ws_expendio/aordenvalidar.aspx?wsdl</wsdlLocation>
                            <staleFile>${project.build.directory}/jaxws/stale/aordenvalidar.aspx.stale</staleFile>
                        </configuration>
                        <id>wsimport-generate-aordenvalidar.aspx</id>
                        <phase>generate-sources</phase>
                    </execution>
                    <execution>
                        <goals>
                            <goal>wsimport</goal>
                        </goals>
                        <configuration>
                            <wsdlFiles>
                                <wsdlFile>rproxy.cobituc.info/ws_expendio/aordendevolver.aspx.wsdl</wsdlFile>
                            </wsdlFiles>
                            <packageName>ClienteIPSST5</packageName>
                            <vmArgs>
                                <vmArg>-Djavax.xml.accessExternalSchema=all</vmArg>
                            </vmArgs>
                            <wsdlLocation>http://rproxy.cobituc.info/ws_expendio/aordendevolver.aspx?wsdl</wsdlLocation>
                            <staleFile>${project.build.directory}/jaxws/stale/aordendevolver.aspx.stale</staleFile>
                        </configuration>
                        <id>wsimport-generate-aordendevolver.aspx</id>
                        <phase>generate-sources</phase>
                    </execution>
                    <execution>
                        <goals>
                            <goal>wsimport</goal>
                        </goals>
                        <configuration>
                            <wsdlFiles>
                                <wsdlFile>rproxy.cobituc.info/ws_expendio/aordenvalidadaanular.aspx.wsdl</wsdlFile>
                            </wsdlFiles>
                            <packageName>ClienteIPSST6</packageName>
                            <vmArgs>
                                <vmArg>-Djavax.xml.accessExternalSchema=all</vmArg>
                            </vmArgs>
                            <wsdlLocation>http://rproxy.cobituc.info/ws_expendio/aordenvalidadaanular.aspx?wsdl</wsdlLocation>
                            <staleFile>${project.build.directory}/jaxws/stale/aordenvalidadaanular.aspx.stale</staleFile>
                        </configuration>
                        <id>wsimport-generate-aordenvalidadaanular.aspx</id>
                        <phase>generate-sources</phase>
                    </execution>
                    <execution>
                        <goals>
                            <goal>wsimport</goal>
                        </goals>
                        <configuration>
                            <wsdlFiles>
                                <wsdlFile>rproxy.cobituc.info_9011/AgenteServicios.svc.wsdl</wsdlFile>
                            </wsdlFiles>
                            <packageName>ClienteJerarquicos</packageName>
                            <vmArgs>
                                <vmArg>-Djavax.xml.accessExternalSchema=all</vmArg>
                            </vmArgs>
                            <wsdlLocation>http://rproxy.cobituc.info:9011/AgenteServicios.svc?wsdl</wsdlLocation>
                            <staleFile>${project.build.directory}/jaxws/stale/AgenteServicios.svc.stale</staleFile>
                        </configuration>
                        <id>wsimport-generate-AgenteServicios.svc</id>
                        <phase>generate-sources</phase>
                    </execution>
                    <execution>
                        <goals>
                            <goal>wsimport</goal>
                        </goals>
                        <configuration>
                            <wsdlFiles>
                                <wsdlFile>ws.ipsst.gov.ar_8543/ws_expendio/aafiliadopuedeconsumir.aspx.wsdl</wsdlFile>
                            </wsdlFiles>
                            <packageName>ClienteIPSST1</packageName>
                            <vmArgs>
                                <vmArg>-Djavax.xml.accessExternalSchema=all</vmArg>
                            </vmArgs>
                            <wsdlLocation>https://ws.ipsst.gov.ar:8543/ws_expendio/aafiliadopuedeconsumir.aspx?wsdl</wsdlLocation>
                            <staleFile>${project.build.directory}/jaxws/stale/aafiliadopuedeconsumir.aspx_1.stale</staleFile>
                        </configuration>
                        <id>wsimport-generate-aafiliadopuedeconsumir.aspx_1</id>
                        <phase>generate-sources</phase>
                    </execution>
                    <execution>
                        <goals>
                            <goal>wsimport</goal>
                        </goals>
                        <configuration>
                            <wsdlFiles>
                                <wsdlFile>canalws.traditum.com/WebService_IA.asmx.wsdl</wsdlFile>
                            </wsdlFiles>
                            <packageName>ClienteMedife</packageName>
                            <vmArgs>
                                <vmArg>-Djavax.xml.accessExternalSchema=all</vmArg>
                            </vmArgs>
                            <wsdlLocation>https://canalws.traditum.com/WebService_IA.asmx?WSDL</wsdlLocation>
                            <staleFile>${project.build.directory}/jaxws/stale/WebService_IA.asmx.stale</staleFile>
                        </configuration>
                        <id>wsimport-generate-WebService_IA.asmx</id>
                        <phase>generate-sources</phase>
                    </execution>
                    <execution>
                        <goals>
                            <goal>wsimport</goal>
                        </goals>
                        <configuration>
                            <wsdlFiles>
                                <wsdlFile>servicioweb.nobissalud.com.ar/wsGecrosNet.asmx.wsdl</wsdlFile>
                            </wsdlFiles>
                            <packageName>ClienteNobis</packageName>
                            <vmArgs>
                                <vmArg>-Djavax.xml.accessExternalSchema=all</vmArg>
                            </vmArgs>
                            <wsdlLocation>https://servicioweb.nobissalud.com.ar/wsGecrosNet.asmx?WSDL</wsdlLocation>
                            <staleFile>${project.build.directory}/jaxws/stale/wsGecrosNet.asmx.stale</staleFile>
                        </configuration>
                        <id>wsimport-generate-wsGecrosNet.asmx</id>
                        <phase>generate-sources</phase>
                    </execution>
                    <execution>
                        <goals>
                            <goal>wsimport</goal>
                        </goals>
                        <configuration>
                            <wsdlFiles>
                                <wsdlFile>wsconectado.activiaweb.com.ar/WSActiviaC.asmx.wsdl</wsdlFile>
                            </wsdlFiles>
                            <packageName>ClienteOspe</packageName>
                            <vmArgs>
                                <vmArg>-Djavax.xml.accessExternalSchema=all</vmArg>
                            </vmArgs>
                            <wsdlLocation>http://wsconectado.activiaweb.com.ar/WSActiviaC.asmx?WSDL</wsdlLocation>
                            <staleFile>${project.build.directory}/jaxws/stale/WSActiviaC.asmx.stale</staleFile>
                        </configuration>
                        <id>wsimport-generate-WSActiviaC.asmx</id>
                        <phase>generate-sources</phase>
                    </execution>
                    <execution>
                        <goals>
                            <goal>wsimport</goal>
                        </goals>
                        <configuration>
                            <wsdlFiles>
                                <wsdlFile>e.sancorsalud.com.ar/APAWE_SSA_V2.aspx.wsdl</wsdlFile>
                            </wsdlFiles>
                            <packageName>ClienteSancor</packageName>
                            <vmArgs>
                                <vmArg>-Djavax.xml.accessExternalSchema=all</vmArg>
                            </vmArgs>
                            <wsdlLocation>http://e.sancorsalud.com.ar/APAWE_SSA_V2.aspx?wsdl</wsdlLocation>
                            <staleFile>${project.build.directory}/jaxws/stale/APAWE_SSA_V2.aspx.stale</staleFile>
                        </configuration>
                        <id>wsimport-generate-APAWE_SSA_V2.aspx</id>
                        <phase>generate-sources</phase>
                    </execution>
                    <execution>
                        <goals>
                            <goal>wsimport</goal>
                        </goals>
                        <configuration>
                            <wsdlFiles>
                                <wsdlFile>testservicios.sancorsalud.com.ar/autorizador/wsdl/hl7v24.wsdl</wsdlFile>
                            </wsdlFiles>
                            <packageName>ClienteSancorHL7</packageName>
                            <vmArgs>
                                <vmArg>-Djavax.xml.accessExternalSchema=all</vmArg>
                            </vmArgs>
                            <wsdlLocation>https://testservicios.sancorsalud.com.ar/Autorizador/WSDL/HL7v24</wsdlLocation>
                            <staleFile>${project.build.directory}/jaxws/stale/hl7v24.stale</staleFile>
                        </configuration>
                        <id>wsimport-generate-hl7v24</id>
                        <phase>generate-sources</phase>
                    </execution>
                    <execution>
                        <goals>
                            <goal>wsimport</goal>
                        </goals>
                        <configuration>
                            <wsdlFiles>
                                <wsdlFile>testservicios.sancorsalud.com.ar/autorizador/wsdl/hl7v24.wsdl</wsdlFile>
                            </wsdlFiles>
                            <packageName>ClienteSancorTest</packageName>
                            <vmArgs>
                                <vmArg>-Djavax.xml.accessExternalSchema=all</vmArg>
                            </vmArgs>
                            <wsdlLocation>https://testservicios.sancorsalud.com.ar/Autorizador/WSDL/HL7v24</wsdlLocation>
                            <staleFile>${project.build.directory}/jaxws/stale/hl7v24_1.stale</staleFile>
                        </configuration>
                        <id>wsimport-generate-hl7v24_1</id>
                        <phase>generate-sources</phase>
                    </execution>
                    <execution>
                        <goals>
                            <goal>wsimport</goal>
                        </goals>
                        <configuration>
                            <wsdlFiles>
                                <wsdlFile>servicios.sancorsalud.com.ar/autorizador/wsdl/hl7v24.wsdl</wsdlFile>
                            </wsdlFiles>
                            <packageName>ClienteSancorPro</packageName>
                            <vmArgs>
                                <vmArg>-Djavax.xml.accessExternalSchema=all</vmArg>
                            </vmArgs>
                            <wsdlLocation>https://servicios.sancorsalud.com.ar/Autorizador/WSDL/HL7v24</wsdlLocation>
                            <staleFile>${project.build.directory}/jaxws/stale/hl7v24_2.stale</staleFile>
                        </configuration>
                        <id>wsimport-generate-hl7v24_2</id>
                        <phase>generate-sources</phase>
                    </execution>
                    <execution>
                        <goals>
                            <goal>wsimport</goal>
                        </goals>
                        <configuration>
                            <wsdlFiles>
                                <wsdlFile>tdm-canalws-soap-testing.azurewebsites.net/WebService_IA.asmx.wsdl</wsdlFile>
                            </wsdlFiles>
                            <packageName>ClientePrevencionTest</packageName>
                            <vmArgs>
                                <vmArg>-Djavax.xml.accessExternalSchema=all</vmArg>
                            </vmArgs>
                            <wsdlLocation>https://tdm-canalws-soap-testing.azurewebsites.net/WebService_IA.asmx?WSDL</wsdlLocation>
                            <staleFile>${project.build.directory}/jaxws/stale/WebService_IA.asmx_1.stale</staleFile>
                        </configuration>
                        <id>wsimport-generate-WebService_IA.asmx_1</id>
                        <phase>generate-sources</phase>
                    </execution>
                    <execution>
                        <goals>
                            <goal>wsimport</goal>
                        </goals>
                        <configuration>
                            <wsdlFiles>
                                <wsdlFile>canalws.traditum.com/WebService_IA.asmx.wsdl</wsdlFile>
                            </wsdlFiles>
                            <packageName>ClientePrevencion</packageName>
                            <vmArgs>
                                <vmArg>-Djavax.xml.accessExternalSchema=all</vmArg>
                            </vmArgs>
                            <wsdlLocation>https://canalws.traditum.com/WebService_IA.asmx?WSDL</wsdlLocation>
                            <staleFile>${project.build.directory}/jaxws/stale/WebService_IA.asmx_2.stale</staleFile>
                        </configuration>
                        <id>wsimport-generate-WebService_IA.asmx_2</id>
                        <phase>generate-sources</phase>
                    </execution>
                    <execution>
                        <goals>
                            <goal>wsimport</goal>
                        </goals>
                        <configuration>
                            <wsdlFiles>
                                <wsdlFile>autogestion.asunt.org.ar_80/WSP-pruebas/wsp.wsdl</wsdlFile>
                            </wsdlFiles>
                            <packageName>ClienteAsunt</packageName>
                            <vmArgs>
                                <vmArg>-Djavax.xml.accessExternalSchema=all</vmArg>
                            </vmArgs>
                            <wsdlLocation>http://autogestion.asunt.org.ar:80/WSP-pruebas/wsp?wsdl</wsdlLocation>
                            <staleFile>${project.build.directory}/jaxws/stale/wsp.stale</staleFile>
                        </configuration>
                        <id>wsimport-generate-wsp</id>
                        <phase>generate-sources</phase>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>jakarta.xml.bind</groupId>
                        <artifactId>jakarta.xml.bind-api</artifactId>
                        <version>4.0.2</version>
                    </dependency>
                    <dependency>
                        <groupId>jakarta.xml.ws</groupId>
                        <artifactId>jakarta.xml.ws-api</artifactId>
                        <version>4.0.1</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <sourceDestDir>${project.build.directory}/generated-sources/jaxws-wsimport</sourceDestDir>
                    <xnocompile>true</xnocompile>
                    <verbose>true</verbose>
                    <extension>true</extension>
                    <catalog>${basedir}/src/jax-ws-catalog.xml</catalog>
                </configuration>
            </plugin>
            
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>1.2</version>
            </plugin>

            <plugin>
                <artifactId>                    
                    maven-assembly-plugin
                </artifactId>
                <configuration>
                    <archive>
                        <manifest>
                            <mainClass>Formularios.Inicio</mainClass> 
                        </manifest>
                    </archive>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                </configuration>
            </plugin>
            
        </plugins>
    </build>
    <dependencies>
        <dependency>
            <groupId>net.sourceforge.barbecue</groupId>
            <artifactId>barbecue</artifactId>
            <version>1.5-beta1</version>
        </dependency>
        <dependency>
            <groupId>org.mariadb.jdbc</groupId>
            <artifactId>mariadb-java-client</artifactId>
            <version>3.4.1</version>
        </dependency>
        <dependency>
            <groupId>net.sf.jasperreports</groupId>
            <artifactId>jasperreports</artifactId>
            <version>7.0.6</version>
        </dependency>
        <dependency>
            <groupId>net.sf.jasperreports</groupId>
            <artifactId>jasperreports-pdf</artifactId>
            <version>7.0.6</version>
        </dependency>
        <dependency>
            <groupId>net.sf.jasperreports</groupId>
            <artifactId>jasperreports-jdt</artifactId>
            <version>7.0.6</version>
        </dependency>
        <dependency>
            <groupId>jakarta.xml.ws</groupId>
            <artifactId>jakarta.xml.ws-api</artifactId>
            <version>4.0.1</version>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.ws</groupId>
            <artifactId>jaxws-rt</artifactId>
            <version>4.0.3</version>
        </dependency>
        <dependency>
            <groupId>jakarta.xml.bind</groupId>
            <artifactId>jakarta.xml.bind-api</artifactId>
            <version>4.0.2</version>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-impl</artifactId>
            <version>4.0.5</version>
        </dependency>
        <dependency>
            <groupId>org.jdom</groupId>
            <artifactId>jdom2</artifactId>
            <version>2.0.6</version>
            <type>jar</type>
        </dependency>        
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.13.2</version>
            <scope>compile</scope>
        </dependency>     
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-client</artifactId>
            <version>6.2.10.Final</version>
        </dependency>
        <dependency>
            <groupId>jakarta.json</groupId>
            <artifactId>jakarta.json-api</artifactId>
            <version>2.1.3</version>
        </dependency>
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20240303</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>net.sourceforge.jexcelapi</groupId>
            <artifactId>jxl</artifactId>
            <version>2.6.12</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>org.swinglabs.swingx</groupId>
            <artifactId>swingx-autocomplete</artifactId>
            <version>1.6.5-1</version>
            <type>jar</type>
        </dependency>        
        <dependency>
            <groupId>com.mxrck</groupId>
            <artifactId>AutoCompleter</artifactId>
            <version>2.0.1</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.18.3</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>2.18.3</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>2.18.3</version>
        </dependency>
        <dependency>
            <groupId>com.github.librepdf</groupId>
            <artifactId>openpdf</artifactId>
            <version>1.3.43</version>
        </dependency>
        
        <dependency>
            <groupId>com.toedter</groupId>
            <artifactId>jcalendar</artifactId>
            <version>1.4</version>
        </dependency>    
                
        <dependency>
            <groupId>org</groupId>
            <artifactId>netbeans</artifactId>
            <version>82</version>
        </dependency>                        
    </dependencies>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.release>26</maven.compiler.release>
    </properties>

    <profiles>
        <!--
            Perfil "bundle": genera un ejecutable Windows autónomo (app-image) con un
            JRE mínimo embebido, así el usuario final NO necesita tener Java instalado.

            Uso:   mvn clean verify -Pbundle
            Salida: target/dist-min/Facturacion/  (Facturacion.exe + app/ + runtime/)

            Requiere un JDK que incluya la carpeta 'jmods' (Temurin NO la trae).
            Por eso se usa un Zulu JDK 26. Si está en otra ruta, sobreescribir con:
                mvn clean verify -Pbundle -Dbundle.jdk.home="C:\ruta\al\zulu-jdk"
        -->
        <profile>
            <id>bundle</id>
            <properties>
                <bundle.jdk.home>C:\Users\ferna\tools\zulu-jdk26\zulu26.30.11-ca-jdk26.0.1-win_x64</bundle.jdk.home>
            </properties>
            <build>
                <plugins>
                    <!-- Limpia salidas previas para que jlink/jpackage no fallen en reruns -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-clean-plugin</artifactId>
                        <version>3.4.0</version>
                        <executions>
                            <execution>
                                <id>clean-bundle-dirs</id>
                                <phase>prepare-package</phase>
                                <goals>
                                    <goal>clean</goal>
                                </goals>
                                <configuration>
                                    <excludeDefaultDirectories>true</excludeDefaultDirectories>
                                    <filesets>
                                        <fileset>
                                            <directory>${project.build.directory}/jre-min</directory>
                                        </fileset>
                                        <fileset>
                                            <directory>${project.build.directory}/dist-min</directory>
                                        </fileset>
                                        <fileset>
                                            <directory>${project.build.directory}/app-input</directory>
                                        </fileset>
                                    </filesets>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>

                    <!-- 1) Arma el jar-with-dependencies dentro de target/app-input -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-assembly-plugin</artifactId>
                        <version>3.7.1</version>
                        <executions>
                            <execution>
                                <id>bundle-fatjar</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>single</goal>
                                </goals>
                                <configuration>
                                    <outputDirectory>${project.build.directory}/app-input</outputDirectory>
                                    <!-- Nombre FIJO del jar: la auto-actualización siempre reemplaza este archivo -->
                                    <finalName>Facturacion</finalName>
                                    <appendAssemblyId>false</appendAssemblyId>
                                    <archive>
                                        <manifest>
                                            <mainClass>Formularios.Inicio</mainClass>
                                        </manifest>
                                    </archive>
                                    <descriptorRefs>
                                        <descriptorRef>jar-with-dependencies</descriptorRef>
                                    </descriptorRefs>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>

                    <!-- 2) jlink crea el runtime mínimo  3) jpackage arma el .exe -->
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>3.1.0</version>
                        <executions>
                            <!-- Runtime mínimo (solo módulos que usa la app + locales es/en) -->
                            <execution>
                                <id>jlink-runtime</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                                <configuration>
                                    <executable>${bundle.jdk.home}\bin\jlink.exe</executable>
                                    <arguments>
                                        <argument>--module-path=${bundle.jdk.home}\jmods</argument>
                                        <argument>--add-modules=java.se,jdk.crypto.ec,jdk.crypto.mscapi,jdk.charsets,jdk.zipfs,jdk.unsupported,jdk.security.auth,jdk.localedata</argument>
                                        <argument>--include-locales=en,es</argument>
                                        <argument>--strip-debug</argument>
                                        <argument>--no-header-files</argument>
                                        <argument>--no-man-pages</argument>
                                        <argument>--compress=zip-6</argument>
                                        <argument>--output=${project.build.directory}/jre-min</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                            <!-- Ejecutable nativo Windows con el runtime embebido -->
                            <execution>
                                <id>jpackage-app-image</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                                <configuration>
                                    <executable>${bundle.jdk.home}\bin\jpackage.exe</executable>
                                    <arguments>
                                        <argument>--type=app-image</argument>
                                        <argument>--name=Facturacion</argument>
                                        <argument>--input=${project.build.directory}/app-input</argument>
                                        <argument>--main-jar=Facturacion.jar</argument>
                                        <argument>--main-class=Formularios.Inicio</argument>
                                        <argument>--runtime-image=${project.build.directory}/jre-min</argument>
                                        <argument>--dest=${project.build.directory}/dist-min</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

    <name>FacturacionMavenMariadb</name>
</project>