<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.mycompany</groupId>
    <artifactId>FacturacionMavenMariadb</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>
    <build>
        <resources>
            <resource>                
                <targetPath>META-INF</targetPath>
                <directory>src</directory>
                <includes>
                    <include>jax-ws-catalog.xml</include>
                    <include>wsdl/**</include>
                </includes>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
            </resource>
        </resources>
        <plugins>                 
            <plugin>
                <groupId>org.jvnet.jax-ws-commons</groupId>
                <artifactId>jaxws-maven-plugin</artifactId>
                <version>2.3</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>wsimport</goal>
                        </goals>
                        <configuration>
                            <wsdlFiles>
                                <wsdlFile>rproxy.cobituc.info_5480/WsBoreal/servlet/awsboreal.wsdl</wsdlFile>
                            </wsdlFiles>
                            <packageName>ClienteBoreal</packageName>
                            <vmArgs>
                                <vmArg>-Djavax.xml.accessExternalSchema=all</vmArg>
                            </vmArgs>
                            <wsdlLocation>http://rproxy.cobituc.info:5480/WsBoreal/servlet/awsboreal?wsdl</wsdlLocation>
                            <staleFile>${project.build.directory}/jaxws/stale/awsboreal.stale</staleFile>
                        </configuration>
                        <id>wsimport-generate-awsboreal</id>
                        <phase>generate-sources</phase>
                    </execution>
                    <execution>
                        <goals>
                            <goal>wsimport</goal>
                        </goals>
                        <configuration>
                             <wsdlFiles>
                                <wsdlFile>ws.ipsst.gov.ar_8543/ws_expendio/aafiliadopuedeconsumir.aspx.wsdl</wsdlFile>
                            </wsdlFiles>
                            <packageName>ClienteIPSST1</packageName>
                             <vmArgs>
                                <vmArg>-Djavax.xml.accessExternalSchema=all</vmArg>  
                                <vmArg>-Djsse.enableSNIExtension=false</vmArg>  
                                <vmOptions>-Djsse.enableSNIExtension=false</vmOptions>
                            </vmArgs>
                            <wsdlLocation>https://ws.ipsst.gov.ar:8543/ws_expendio/aafiliadopuedeconsumir.aspx?wsdl</wsdlLocation>
                            <staleFile>${project.build.directory}/jaxws/stale/aafiliadopuedeconsumir.aspx.stale</staleFile>
                        </configuration>
                        <id>wsimport-generate-aafiliadopuedeconsumir.aspx</id>
                        <phase>generate-sources</phase>
                    </execution>
                    <execution>
                        <goals>
                            <goal>wsimport</goal>
                        </goals>
                        <configuration>
                            <wsdlFiles>
                                <wsdlFile>rproxy.cobituc.info/ws_expendio/aafiliadodatostraer.aspx.wsdl</wsdlFile>
                            </wsdlFiles>
                            <packageName>ClienteIPSST2</packageName>
                            <vmArgs>
                                <vmArg>-Djavax.xml.accessExternalSchema=all</vmArg>
                            </vmArgs>
                            <wsdlLocation>http://rproxy.cobituc.info/ws_expendio/aafiliadodatostraer.aspx?wsdl</wsdlLocation>
                            <staleFile>${project.build.directory}/jaxws/stale/aafiliadodatostraer.aspx.stale</staleFile>
                        </configuration>
                        <id>wsimport-generate-aafiliadodatostraer.aspx</id>
                        <phase>generate-sources</phase>
                    </execution>
                    <execution>
                        <goals>
                            <goal>wsimport</goal>
                        </goals>
                        <configuration>
                            <wsdlFiles>
                                <wsdlFile>rproxy.cobituc.info/ws_expendio/aordenautorizar.aspx.wsdl</wsdlFile>
                            </wsdlFiles>
                            <packageName>ClienteIPSST3</packageName>
                            <vmArgs>
                                <vmArg>-Djavax.xml.accessExternalSchema=all</vmArg>
                            </vmArgs>
                            <wsdlLocation>http://rproxy.cobituc.info/ws_expendio/aordenautorizar.aspx?wsdl</wsdlLocation>
                            <staleFile>${project.build.directory}/jaxws/stale/aordenautorizar.aspx.stale</staleFile>
                        </configuration>
                        <id>wsimport-generate-aordenautorizar.aspx</id>
                        <phase>generate-sources</phase>
                    </execution>
                    <execution>
                        <goals>
                            <goal>wsimport</goal>
                        </goals>
                        <configuration>
                            <wsdlFiles>
                                <wsdlFile>rproxy.cobituc.info/ws_expendio/aordenvalidar.aspx.wsdl</wsdlFile>
                            </wsdlFiles>
                            <packageName>ClienteIPSST4</packageName>
                            <vmArgs>
                                <vmArg>-Djavax.xml.accessExternalSchema=all</vmArg>
                            </vmArgs>
                            <wsdlLocation>http://rproxy.cobituc.info/ws_expendio/aordenvalidar.aspx?wsdl</wsdlLocation>
                            <staleFile>${project.build.directory}/jaxws/stale/aordenvalidar.aspx.stale</staleFile>
                        </configuration>
                        <id>wsimport-generate-aordenvalidar.aspx</id>
                        <phase>generate-sources</phase>
                    </execution>
                    <execution>
                        <goals>
                            <goal>wsimport</goal>
                        </goals>
                        <configuration>
                            <wsdlFiles>
                                <wsdlFile>rproxy.cobituc.info/ws_expendio/aordendevolver.aspx.wsdl</wsdlFile>
                            </wsdlFiles>
                            <packageName>ClienteIPSST5</packageName>
                            <vmArgs>
                                <vmArg>-Djavax.xml.accessExternalSchema=all</vmArg>
                            </vmArgs>
                            <wsdlLocation>http://rproxy.cobituc.info/ws_expendio/aordendevolver.aspx?wsdl</wsdlLocation>
                            <staleFile>${project.build.directory}/jaxws/stale/aordendevolver.aspx.stale</staleFile>
                        </configuration>
                        <id>wsimport-generate-aordendevolver.aspx</id>
                        <phase>generate-sources</phase>
                    </execution>
                    <execution>
                        <goals>
                            <goal>wsimport</goal>
                        </goals>
                        <configuration>
                            <wsdlFiles>
                                <wsdlFile>rproxy.cobituc.info/ws_expendio/aordenvalidadaanular.aspx.wsdl</wsdlFile>
                            </wsdlFiles>
                            <packageName>ClienteIPSST6</packageName>
                            <vmArgs>
                                <vmArg>-Djavax.xml.accessExternalSchema=all</vmArg>
                            </vmArgs>
                            <wsdlLocation>http://rproxy.cobituc.info/ws_expendio/aordenvalidadaanular.aspx?wsdl</wsdlLocation>
                            <staleFile>${project.build.directory}/jaxws/stale/aordenvalidadaanular.aspx.stale</staleFile>
                        </configuration>
                        <id>wsimport-generate-aordenvalidadaanular.aspx</id>
                        <phase>generate-sources</phase>
                    </execution>
                    <execution>
                        <goals>
                            <goal>wsimport</goal>
                        </goals>
                        <configuration>
                            <wsdlFiles>
                                <wsdlFile>rproxy.cobituc.info_9011/AgenteServicios.svc.wsdl</wsdlFile>
                            </wsdlFiles>
                            <packageName>ClienteJerarquicos</packageName>
                            <vmArgs>
                                <vmArg>-Djavax.xml.accessExternalSchema=all</vmArg>
                            </vmArgs>
                            <wsdlLocation>http://rproxy.cobituc.info:9011/AgenteServicios.svc?wsdl</wsdlLocation>
                            <staleFile>${project.build.directory}/jaxws/stale/AgenteServicios.svc.stale</staleFile>
                        </configuration>
                        <id>wsimport-generate-AgenteServicios.svc</id>
                        <phase>generate-sources</phase>
                    </execution>
                    <execution>
                        <goals>
                            <goal>wsimport</goal>
                        </goals>
                        <configuration>
                            <wsdlFiles>
                                <wsdlFile>ws.ipsst.gov.ar_8543/ws_expendio/aafiliadopuedeconsumir.aspx.wsdl</wsdlFile>
                            </wsdlFiles>
                            <packageName>ClienteIPSST1</packageName>
                            <vmArgs>
                                <vmArg>-Djavax.xml.accessExternalSchema=all</vmArg>
                            </vmArgs>
                            <wsdlLocation>https://ws.ipsst.gov.ar:8543/ws_expendio/aafiliadopuedeconsumir.aspx?wsdl</wsdlLocation>
                            <staleFile>${project.build.directory}/jaxws/stale/aafiliadopuedeconsumir.aspx_1.stale</staleFile>
                        </configuration>
                        <id>wsimport-generate-aafiliadopuedeconsumir.aspx_1</id>
                        <phase>generate-sources</phase>
                    </execution>
                    <execution>
                        <goals>
                            <goal>wsimport</goal>
                        </goals>
                        <configuration>
                            <wsdlFiles>
                                <wsdlFile>canalws.traditum.com/WebService_IA.asmx.wsdl</wsdlFile>
                            </wsdlFiles>
                            <packageName>ClienteMedife</packageName>
                            <vmArgs>
                                <vmArg>-Djavax.xml.accessExternalSchema=all</vmArg>
                            </vmArgs>
                            <wsdlLocation>https://canalws.traditum.com/WebService_IA.asmx?WSDL</wsdlLocation>
                            <staleFile>${project.build.directory}/jaxws/stale/WebService_IA.asmx.stale</staleFile>
                        </configuration>
                        <id>wsimport-generate-WebService_IA.asmx</id>
                        <phase>generate-sources</phase>
                    </execution>
                    <execution>
                        <goals>
                            <goal>wsimport</goal>
                        </goals>
                        <configuration>
                            <wsdlFiles>
                                <wsdlFile>servicioweb.nobissalud.com.ar/wsGecrosNet.asmx.wsdl</wsdlFile>
                            </wsdlFiles>
                            <packageName>ClienteNobis</packageName>
                            <vmArgs>
                                <vmArg>-Djavax.xml.accessExternalSchema=all</vmArg>
                            </vmArgs>
                            <wsdlLocation>https://servicioweb.nobissalud.com.ar/wsGecrosNet.asmx?WSDL</wsdlLocation>
                            <staleFile>${project.build.directory}/jaxws/stale/wsGecrosNet.asmx.stale</staleFile>
                        </configuration>
                        <id>wsimport-generate-wsGecrosNet.asmx</id>
                        <phase>generate-sources</phase>
                    </execution>
                    <execution>
                        <goals>
                            <goal>wsimport</goal>
                        </goals>
                        <configuration>
                            <wsdlFiles>
                                <wsdlFile>wsconectado.activiaweb.com.ar/WSActiviaC.asmx.wsdl</wsdlFile>
                            </wsdlFiles>
                            <packageName>ClienteOspe</packageName>
                            <vmArgs>
                                <vmArg>-Djavax.xml.accessExternalSchema=all</vmArg>
                            </vmArgs>
                            <wsdlLocation>http://wsconectado.activiaweb.com.ar/WSActiviaC.asmx?WSDL</wsdlLocation>
                            <staleFile>${project.build.directory}/jaxws/stale/WSActiviaC.asmx.stale</staleFile>
                        </configuration>
                        <id>wsimport-generate-WSActiviaC.asmx</id>
                        <phase>generate-sources</phase>
                    </execution>
                    <execution>
                        <goals>
                            <goal>wsimport</goal>
                        </goals>
                        <configuration>
                            <wsdlFiles>
                                <wsdlFile>e.sancorsalud.com.ar/APAWE_SSA_V2.aspx.wsdl</wsdlFile>
                            </wsdlFiles>
                            <packageName>ClienteSancor</packageName>
                            <vmArgs>
                                <vmArg>-Djavax.xml.accessExternalSchema=all</vmArg>
                            </vmArgs>
                            <wsdlLocation>http://e.sancorsalud.com.ar/APAWE_SSA_V2.aspx?wsdl</wsdlLocation>
                            <staleFile>${project.build.directory}/jaxws/stale/APAWE_SSA_V2.aspx.stale</staleFile>
                        </configuration>
                        <id>wsimport-generate-APAWE_SSA_V2.aspx</id>
                        <phase>generate-sources</phase>
                    </execution>
                    <execution>
                        <goals>
                            <goal>wsimport</goal>
                        </goals>
                        <configuration>
                            <wsdlFiles>
                                <wsdlFile>testservicios.sancorsalud.com.ar/autorizador/wsdl/hl7v24.wsdl</wsdlFile>
                            </wsdlFiles>
                            <packageName>ClienteSancorHL7</packageName>
                            <vmArgs>
                                <vmArg>-Djavax.xml.accessExternalSchema=all</vmArg>
                            </vmArgs>
                            <wsdlLocation>https://testservicios.sancorsalud.com.ar/Autorizador/WSDL/HL7v24</wsdlLocation>
                            <staleFile>${project.build.directory}/jaxws/stale/hl7v24.stale</staleFile>
                        </configuration>
                        <id>wsimport-generate-hl7v24</id>
                        <phase>generate-sources</phase>
                    </execution>
                    <execution>
                        <goals>
                            <goal>wsimport</goal>
                        </goals>
                        <configuration>
                            <wsdlFiles>
                                <wsdlFile>testservicios.sancorsalud.com.ar/autorizador/wsdl/hl7v24.wsdl</wsdlFile>
                            </wsdlFiles>
                            <packageName>ClienteSancorTest</packageName>
                            <vmArgs>
                                <vmArg>-Djavax.xml.accessExternalSchema=all</vmArg>
                            </vmArgs>
                            <wsdlLocation>https://testservicios.sancorsalud.com.ar/Autorizador/WSDL/HL7v24</wsdlLocation>
                            <staleFile>${project.build.directory}/jaxws/stale/hl7v24_1.stale</staleFile>
                        </configuration>
                        <id>wsimport-generate-hl7v24_1</id>
                        <phase>generate-sources</phase>
                    </execution>
                    <execution>
                        <goals>
                            <goal>wsimport</goal>
                        </goals>
                        <configuration>
                            <wsdlFiles>
                                <wsdlFile>servicios.sancorsalud.com.ar/autorizador/wsdl/hl7v24.wsdl</wsdlFile>
                            </wsdlFiles>
                            <packageName>ClienteSancorPro</packageName>
                            <vmArgs>
                                <vmArg>-Djavax.xml.accessExternalSchema=all</vmArg>
                            </vmArgs>
                            <wsdlLocation>https://servicios.sancorsalud.com.ar/Autorizador/WSDL/HL7v24</wsdlLocation>
                            <staleFile>${project.build.directory}/jaxws/stale/hl7v24_2.stale</staleFile>
                        </configuration>
                        <id>wsimport-generate-hl7v24_2</id>
                        <phase>generate-sources</phase>
                    </execution>
                </executions>
                <dependencies>                    
                    <dependency>
                        <groupId>javax.xml.bind</groupId>
                        <artifactId>jaxb-api</artifactId>
                        <version>2.1</version>
                    </dependency>
                    
                    <dependency>
                        <groupId>javax.xml</groupId>
                        <artifactId>webservices-api</artifactId>
                        <version>2.0</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <sourceDestDir>${project.build.directory}/generated-sources/jaxws-wsimport</sourceDestDir>
                    <xnocompile>true</xnocompile>
                    <verbose>true</verbose>
                    <extension>true</extension>
                    <catalog>${basedir}/src/jax-ws-catalog.xml</catalog>
                </configuration>
            </plugin>
            
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>1.2</version>
            </plugin>
            <plugin>
                <artifactId>                    
                    maven-assembly-plugin
                </artifactId>
                <configuration>
                    <archive>
                        <manifest>
                            <mainClass>Formularios.Inicio</mainClass> 
                        </manifest>
                    </archive>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                </configuration>
            </plugin>
            
        </plugins>
    </build>
    <dependencies>
        <dependency>
            <groupId>net.sourceforge.barbecue</groupId>
            <artifactId>barbecue</artifactId>
            <version>1.5-beta1</version>
        </dependency>
        <dependency>
            <groupId>org.mariadb.jdbc</groupId>
            <artifactId>mariadb-java-client</artifactId>
            <version>2.3.0</version>
        </dependency>         
        <dependency>
            <groupId>net.sf.jasperreports</groupId>
            <artifactId>jasperreports</artifactId>
            <version>6.5.1</version>
        </dependency>                          
        <dependency>
            <groupId>javax.xml</groupId>
            <artifactId>webservices-api</artifactId>
            <version>2.0</version>
        </dependency>
        <dependency>
            <groupId>org.jdom</groupId>
            <artifactId>jdom2</artifactId>
            <version>2.0.6</version>
            <type>jar</type>
        </dependency>        
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.8.6</version>
            <type>jar</type>
        </dependency>      
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-client</artifactId>
            <version>3.1.0.Final</version>
        </dependency>
        <dependency>
            <groupId>javax.json</groupId>
            <artifactId>javax.json-api</artifactId>
            <version>1.1.4</version>
        </dependency>
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20180130</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>net.sourceforge.jexcelapi</groupId>
            <artifactId>jxl</artifactId>
            <version>2.6.12</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>org.swinglabs.swingx</groupId>
            <artifactId>swingx-autocomplete</artifactId>
            <version>1.6.5-1</version>
            <type>jar</type>
        </dependency>        
         <dependency>
            <groupId>com.mxrck</groupId>
            <artifactId>AutoCompleter</artifactId>
            <version>2.0.1</version>
            <type>jar</type>
        </dependency>
        
        <dependency>
            <groupId>com.itextpdf</groupId>
            <artifactId>itextpdf</artifactId>
            <version>5.0.6</version>
        </dependency>
        
        <dependency>
            <groupId>com.toedter</groupId>
            <artifactId>jcalendar</artifactId>
            <version>1.4</version>
        </dependency>    
                
        <dependency>
            <groupId>org</groupId>
            <artifactId>netbeans</artifactId>
            <version>82</version>
        </dependency>                        
    </dependencies>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>
    <name>FacturacionMavenMariadb</name>
</project>