<?xml version = "1.0" encoding = "utf-8"?>
<definitions name="PAWE_SSA_V2" targetNamespace="ExtranetSancorsaludEv1" xmlns:wsdlns="ExtranetSancorsaludEv1" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="ExtranetSancorsaludEv1" xmlns:tns1="amssmpx_ev1">
	<types>
		<schema targetNamespace="ExtranetSancorsaludEv1" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" elementFormDefault="qualified">
			<import namespace="amssmpx_ev1" />
			<complexType name="ArrayOfPrestacionesValidar">
				<sequence>
					<element minOccurs="0" maxOccurs="unbounded" name="PrestacionesValidar" type="tns:PrestacionesValidar" form="unqualified">
					</element>
				</sequence>
			</complexType>
			<complexType name="PrestacionesValidar">
				<all>
					<element name="TipoNomenclador" type="xsd:string" form="unqualified">
					</element>
					<element name="Prestacion" type="xsd:string" form="unqualified">
					</element>
				</all>
			</complexType>
			<complexType name="ArrayOfPrestacionesValidarRta">
				<sequence>
					<element minOccurs="0" maxOccurs="unbounded" name="PrestacionesValidarRta" type="tns:PrestacionesValidarRta" form="unqualified">
					</element>
				</sequence>
			</complexType>
			<complexType name="PrestacionesValidarRta">
				<all>
					<element name="TipoNomenclador" type="xsd:string" form="unqualified">
					</element>
					<element name="Prestacion" type="xsd:string" form="unqualified">
					</element>
					<element name="Requiere" type="xsd:string" form="unqualified">
					</element>
				</all>
			</complexType>
			<element name="PAWE_SSA_V2.ELEGIBILIDAD">
				<complexType>
					<sequence>
						<element minOccurs="1" maxOccurs="1" name="Modo" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Entidad" type="xsd:int" />
						<element minOccurs="1" maxOccurs="1" name="Tiponroefector" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Nroefector" type="xsd:long" />
						<element minOccurs="1" maxOccurs="1" name="Formaidafiliado" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Afiliado" type="xsd:long" />
						<element minOccurs="1" maxOccurs="1" name="Usuario" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Clave" type="xsd:string" />
					</sequence>
				</complexType>
			</element>
			<element name="PAWE_SSA_V2.ELEGIBILIDADResponse">
				<complexType>
					<sequence>
						<element minOccurs="1" maxOccurs="1" name="Nombreentidad" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Nombreefector" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Nombreafiliado" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Edad" type="xsd:short" />
						<element minOccurs="1" maxOccurs="1" name="Condicionafiliado" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Codigorespuesta" type="xsd:short" />
						<element minOccurs="1" maxOccurs="1" name="Descripcionrespuesta" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Planrta" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Nombre" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Apellido" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Fechanacimiento" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Nrodocumento" type="xsd:int" />
						<element minOccurs="1" maxOccurs="1" name="Sexo" type="xsd:string" />
					</sequence>
				</complexType>
			</element>
			<element name="PAWE_SSA_V2.AUTORIZACION">
				<complexType>
					<sequence>
						<element minOccurs="1" maxOccurs="1" name="Modo" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Nroorden" type="xsd:int" />
						<element minOccurs="1" maxOccurs="1" name="Entidad" type="xsd:int" />
						<element minOccurs="1" maxOccurs="1" name="Tiponroefector" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Nroefector" type="xsd:long" />
						<element minOccurs="1" maxOccurs="1" name="Formaidafiliado" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Afiliado" type="xsd:long" />
						<element minOccurs="1" maxOccurs="1" name="Matriculaprescribiente" type="xsd:long" />
						<element minOccurs="1" maxOccurs="1" name="Descripcionprescribiente" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Prestaciones" type="tns1:Prestaciones" />
						<element minOccurs="1" maxOccurs="1" name="Usuario" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Clave" type="xsd:string" />
					</sequence>
				</complexType>
			</element>
			<element name="PAWE_SSA_V2.AUTORIZACIONResponse">
				<complexType>
					<sequence>
						<element minOccurs="1" maxOccurs="1" name="Nroautorizacion" type="xsd:int" />
						<element minOccurs="1" maxOccurs="1" name="Nombreentidad" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Nombreefector" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Nombreafiliado" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Edad" type="xsd:short" />
						<element minOccurs="1" maxOccurs="1" name="Condicionafiliado" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Codigorespuesta" type="xsd:short" />
						<element minOccurs="1" maxOccurs="1" name="Descripcionrespuesta" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Planrta" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Prestacionesrtav2" type="tns1:PrestacionesRta" />
						<element minOccurs="1" maxOccurs="1" name="Nombre" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Apellido" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Fechanacimiento" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Nrodocumento" type="xsd:int" />
						<element minOccurs="1" maxOccurs="1" name="Sexo" type="xsd:string" />
					</sequence>
				</complexType>
			</element>
			<element name="PAWE_SSA_V2.ANULACION">
				<complexType>
					<sequence>
						<element minOccurs="1" maxOccurs="1" name="Modo" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Nroautorizacion" type="xsd:int" />
						<element minOccurs="1" maxOccurs="1" name="Entidad" type="xsd:int" />
						<element minOccurs="1" maxOccurs="1" name="Usuario" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Clave" type="xsd:string" />
					</sequence>
				</complexType>
			</element>
			<element name="PAWE_SSA_V2.ANULACIONResponse">
				<complexType>
					<sequence>
						<element minOccurs="1" maxOccurs="1" name="Nroordenrta" type="xsd:int" />
						<element minOccurs="1" maxOccurs="1" name="Nombreentidad" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Codigorespuesta" type="xsd:short" />
						<element minOccurs="1" maxOccurs="1" name="Descripcionrespuesta" type="xsd:string" />
					</sequence>
				</complexType>
			</element>
			<element name="PAWE_SSA_V2.VALIDARPRACTICA">
				<complexType>
					<sequence>
						<element minOccurs="1" maxOccurs="1" name="Modo" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Entidad" type="xsd:int" />
						<element minOccurs="1" maxOccurs="1" name="Formaidafiliado" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Afiliado" type="xsd:long" />
						<element minOccurs="1" maxOccurs="1" name="Prestacionesvalidar" type="tns:ArrayOfPrestacionesValidar" />
						<element minOccurs="1" maxOccurs="1" name="Usuario" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Clave" type="xsd:string" />
					</sequence>
				</complexType>
			</element>
			<element name="PAWE_SSA_V2.VALIDARPRACTICAResponse">
				<complexType>
					<sequence>
						<element minOccurs="1" maxOccurs="1" name="Prestacionesvalidarrta" type="tns:ArrayOfPrestacionesValidarRta" />
						<element minOccurs="1" maxOccurs="1" name="Aviso" type="xsd:string" />
					</sequence>
				</complexType>
			</element>
			<element name="PAWE_SSA_V2.VALIDAR">
				<complexType>
					<sequence>
						<element minOccurs="1" maxOccurs="1" name="Nroorden" type="xsd:int" />
						<element minOccurs="1" maxOccurs="1" name="Entidad" type="xsd:int" />
						<element minOccurs="1" maxOccurs="1" name="Tiponroefector" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Nroefector" type="xsd:long" />
						<element minOccurs="1" maxOccurs="1" name="Formaidafiliado" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Afiliado" type="xsd:long" />
						<element minOccurs="1" maxOccurs="1" name="Matriculaprescribiente" type="xsd:long" />
						<element minOccurs="1" maxOccurs="1" name="Descripcionprescribiente" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Prestaciones" type="tns1:Prestaciones" />
						<element minOccurs="1" maxOccurs="1" name="Usuario" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Clave" type="xsd:string" />
					</sequence>
				</complexType>
			</element>
			<element name="PAWE_SSA_V2.VALIDARResponse">
				<complexType>
					<sequence>
						<element minOccurs="1" maxOccurs="1" name="Nroautorizacion" type="xsd:int" />
						<element minOccurs="1" maxOccurs="1" name="Nombreentidad" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Nombreefector" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Nombreafiliado" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Edad" type="xsd:short" />
						<element minOccurs="1" maxOccurs="1" name="Condicionafiliado" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Codigorespuesta" type="xsd:short" />
						<element minOccurs="1" maxOccurs="1" name="Descripcionrespuesta" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Planrta" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Prestacionesrtav2" type="tns1:PrestacionesRta" />
						<element minOccurs="1" maxOccurs="1" name="Nombre" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Apellido" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Fechanacimiento" type="xsd:string" />
						<element minOccurs="1" maxOccurs="1" name="Nrodocumento" type="xsd:int" />
						<element minOccurs="1" maxOccurs="1" name="Sexo" type="xsd:string" />
					</sequence>
				</complexType>
			</element>
		</schema>
		<schema targetNamespace="amssmpx_ev1" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" elementFormDefault="qualified">
			<import namespace="ExtranetSancorsaludEv1" />
			<complexType name="Prestaciones">
				<all>
					<element name="PrestacionesItem" type="tns1:ArrayOfPrestacionesItem">
					</element>
				</all>
			</complexType>
			<complexType name="ArrayOfPrestacionesItem">
				<sequence>
					<element minOccurs="0" maxOccurs="unbounded" name="PrestacionesItem" type="tns1:PrestacionesItem">
					</element>
				</sequence>
			</complexType>
			<complexType name="PrestacionesItem">
				<all>
					<element name="TipoNomenclador" type="xsd:string">
					</element>
					<element name="Prestacion" type="xsd:string">
					</element>
					<element name="Cantidad" type="xsd:short">
					</element>
					<element name="Formulario" type="xsd:int">
					</element>
				</all>
			</complexType>
			<complexType name="PrestacionesRta">
				<all>
					<element name="PrestacionesRta_PrestacionesRtaItem" type="tns1:ArrayOfPrestacionesRtaItem">
					</element>
				</all>
			</complexType>
			<complexType name="ArrayOfPrestacionesRtaItem">
				<sequence>
					<element minOccurs="0" maxOccurs="unbounded" name="PrestacionesRtaItem" type="tns1:PrestacionesRtaItem">
					</element>
				</sequence>
			</complexType>
			<complexType name="PrestacionesRtaItem">
				<all>
					<element name="ErrorPrestacion" type="xsd:byte">
					</element>
					<element name="TipoNomenclador" type="xsd:string">
					</element>
					<element name="Prestacion" type="xsd:string">
					</element>
					<element name="DescripcionErrorPrest" type="xsd:string">
					</element>
				</all>
			</complexType>
		</schema>
	</types>
	<message name="PAWE_SSA_V2.ELEGIBILIDADSoapIn">
		<part name="parameters" element="tns:PAWE_SSA_V2.ELEGIBILIDAD" />
	</message>
	<message name="PAWE_SSA_V2.ELEGIBILIDADSoapOut">
		<part name="parameters" element="tns:PAWE_SSA_V2.ELEGIBILIDADResponse" />
	</message>
	<message name="PAWE_SSA_V2.AUTORIZACIONSoapIn">
		<part name="parameters" element="tns:PAWE_SSA_V2.AUTORIZACION" />
	</message>
	<message name="PAWE_SSA_V2.AUTORIZACIONSoapOut">
		<part name="parameters" element="tns:PAWE_SSA_V2.AUTORIZACIONResponse" />
	</message>
	<message name="PAWE_SSA_V2.ANULACIONSoapIn">
		<part name="parameters" element="tns:PAWE_SSA_V2.ANULACION" />
	</message>
	<message name="PAWE_SSA_V2.ANULACIONSoapOut">
		<part name="parameters" element="tns:PAWE_SSA_V2.ANULACIONResponse" />
	</message>
	<message name="PAWE_SSA_V2.VALIDARPRACTICASoapIn">
		<part name="parameters" element="tns:PAWE_SSA_V2.VALIDARPRACTICA" />
	</message>
	<message name="PAWE_SSA_V2.VALIDARPRACTICASoapOut">
		<part name="parameters" element="tns:PAWE_SSA_V2.VALIDARPRACTICAResponse" />
	</message>
	<message name="PAWE_SSA_V2.VALIDARSoapIn">
		<part name="parameters" element="tns:PAWE_SSA_V2.VALIDAR" />
	</message>
	<message name="PAWE_SSA_V2.VALIDARSoapOut">
		<part name="parameters" element="tns:PAWE_SSA_V2.VALIDARResponse" />
	</message>
	<portType name="PAWE_SSA_V2SoapPort">
		<operation name="ELEGIBILIDAD">
			<input message="wsdlns:PAWE_SSA_V2.ELEGIBILIDADSoapIn" />
			<output message="wsdlns:PAWE_SSA_V2.ELEGIBILIDADSoapOut" />
		</operation>
		<operation name="AUTORIZACION">
			<input message="wsdlns:PAWE_SSA_V2.AUTORIZACIONSoapIn" />
			<output message="wsdlns:PAWE_SSA_V2.AUTORIZACIONSoapOut" />
		</operation>
		<operation name="ANULACION">
			<input message="wsdlns:PAWE_SSA_V2.ANULACIONSoapIn" />
			<output message="wsdlns:PAWE_SSA_V2.ANULACIONSoapOut" />
		</operation>
		<operation name="VALIDARPRACTICA">
			<input message="wsdlns:PAWE_SSA_V2.VALIDARPRACTICASoapIn" />
			<output message="wsdlns:PAWE_SSA_V2.VALIDARPRACTICASoapOut" />
		</operation>
		<operation name="VALIDAR">
			<input message="wsdlns:PAWE_SSA_V2.VALIDARSoapIn" />
			<output message="wsdlns:PAWE_SSA_V2.VALIDARSoapOut" />
		</operation>
	</portType>
	<binding name="PAWE_SSA_V2SoapBinding" type="wsdlns:PAWE_SSA_V2SoapPort">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
		<operation name="ELEGIBILIDAD">
			<soap:operation soapAction="ExtranetSancorsaludEv1action/APAWE_SSA_V2.ELEGIBILIDAD" />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>
		<operation name="AUTORIZACION">
			<soap:operation soapAction="ExtranetSancorsaludEv1action/APAWE_SSA_V2.AUTORIZACION" />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>
		<operation name="ANULACION">
			<soap:operation soapAction="ExtranetSancorsaludEv1action/APAWE_SSA_V2.ANULACION" />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>
		<operation name="VALIDARPRACTICA">
			<soap:operation soapAction="ExtranetSancorsaludEv1action/APAWE_SSA_V2.VALIDARPRACTICA" />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>
		<operation name="VALIDAR">
			<soap:operation soapAction="ExtranetSancorsaludEv1action/APAWE_SSA_V2.VALIDAR" />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>
	</binding>
	<service name="PAWE_SSA_V2">
		<port name="PAWE_SSA_V2SoapPort" binding="wsdlns:PAWE_SSA_V2SoapBinding">
			<soap:address location="http://e.sancorsalud.com.ar/apawe_ssa_v2.aspx" />
		</port>
	</service>
</definitions>
