<?xml version="1.0" encoding="utf-8"?><xs:schema elementFormDefault="qualified" targetNamespace="http://schemas.datacontract.org/2004/07/Framework.Contratos.Criterios" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://schemas.datacontract.org/2004/07/Framework.Contratos.Criterios"><xs:complexType name="Paginado"><xs:sequence><xs:element minOccurs="0" name="Activado" type="xs:boolean"/><xs:element minOccurs="0" name="NoRetornaDatosPaginado" type="xs:boolean"/><xs:element minOccurs="0" name="PaginaActual" type="xs:int"/><xs:element minOccurs="0" name="TamanioPagina" type="xs:int"/><xs:element minOccurs="0" name="TotalPaginas" type="xs:int"/><xs:element minOccurs="0" name="TotalRegistros" type="xs:int"/></xs:sequence></xs:complexType><xs:element name="Paginado" nillable="true" type="tns:Paginado"/></xs:schema>